# Generated by Django 2.2.4 on 2019-12-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('Owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('uploadfor', models.CharField(blank=True, choices=[('Sell', 'Sell'), ('Rent', 'Rent')], max_length=5, null=True)),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantity', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('avail', models.CharField(blank=True, choices=[('Available', 'Available'), ('!Available', '!Available')], max_length=10, null=True)),
                ('advalue', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10, null=True)),
                ('offer', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=5, null=True)),
                ('post_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('adviewed', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Category')),
            ],
        ),
    ]
