# Generated by Django 2.2.4 on 2019-12-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20191226_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='No Image', upload_to='Ads/'),
        ),
    ]
