# Generated by Django 2.2.4 on 2019-12-27 08:28

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20191226_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Home.models.upload_image_path),
        ),
    ]
