# Generated by Django 2.2.4 on 2020-01-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20191227_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avail',
            field=models.CharField(choices=[('Available', 'Available'), ('!Available', '!Available')], default='!Available', max_length=10),
        ),
    ]
