# Generated by Django 2.2.4 on 2020-03-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_product_rejected_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='verified_status',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='verifier_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='visit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('Ahmedabad', 'Ahmedabad'), ('Bagodara', 'Bagodara')], max_length=20, null=True),
        ),
    ]
