# Generated by Django 2.2.4 on 2020-03-21 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20200321_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='IsActive',
            field=models.BooleanField(default=False, verbose_name=((True, 'Yes'), (False, 'No'))),
        ),
        migrations.AddField(
            model_name='profile',
            name='IsAvailable',
            field=models.BooleanField(default=False, verbose_name=((True, 'Yes'), (False, 'No'))),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.Citymaster'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.CountryMaster'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.Statemaster'),
        ),
    ]
