# Generated by Django 2.2.4 on 2020-03-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20200321_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='Birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
