# Generated by Django 2.2.4 on 2020-03-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_auto_20200321_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='IsActive',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name=((True, 'Yes'), (False, 'No'))),
        ),
        migrations.AlterField(
            model_name='profile',
            name='IsAvailable',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name=((True, 'Yes'), (False, 'No'))),
        ),
    ]
