# Generated by Django 2.2.4 on 2020-03-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20200321_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='IsActive',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='IsAvailable',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
