# Generated by Django 2.2.4 on 2020-03-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_auto_20200321_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='OtherBrand',
        ),
    ]
