# Generated by Django 2.2.4 on 2020-03-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_remove_product_otherbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Old', 'Old')], max_length=5, null=True),
        ),
    ]
