# Generated by Django 2.2.4 on 2020-03-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_auto_20200322_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ApprovedBy',
            new_name='ApprovedOrRejectedBy',
        ),
    ]
