# Generated by Django 2.2.4 on 2020-03-26 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0020_auto_20200326_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producttransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takendate', models.DateField(blank=True, null=True)),
                ('returndte', models.DateField(blank=True, null=True)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('productid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('PaymentType', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Createddate', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('Merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Paymentfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Product')),
            ],
        ),
    ]
