# Generated by Django 2.2.4 on 2020-03-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_payment_producttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='IsProductSoldOrOnRent',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
