# Generated by Django 2.2.4 on 2020-03-21 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Statemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StateName', models.CharField(max_length=50)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.CountryMaster')),
            ],
        ),
        migrations.CreateModel(
            name='Citymaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=50)),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.Statemaster')),
            ],
        ),
    ]
