# Generated by Django 2.2.4 on 2020-03-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_citymaster_countrymaster_statemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brandmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=50)),
                ('BrandUrl', models.CharField(max_length=255)),
                ('BrandLogo', models.ImageField(blank=True, null=True, upload_to='')),
                ('IsActive', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='City',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.Citymaster'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.CountryMaster'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Postcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='State',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.Statemaster'),
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=255, unique=True)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Postcode', models.CharField(blank=True, max_length=6, null=True)),
                ('Birthdate', models.DateField()),
                ('IdProof', models.FileField(blank=True, null=True, upload_to='')),
                ('AddressProof', models.FileField(blank=True, null=True, upload_to='')),
                ('IsActive', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('IsAvailable', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('City', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.Citymaster')),
                ('Country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.CountryMaster')),
                ('State', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.Statemaster')),
            ],
        ),
    ]
