# Generated by Django 2.2.4 on 2020-03-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='Password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='Phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='Username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
