# Generated by Django 2.2.4 on 2020-03-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0013_auto_20200321_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMasterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoryname', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReportedBy', models.IntegerField()),
                ('ReportotherCategory', models.CharField(blank=True, max_length=50, null=True)),
                ('ReportMessage', models.TextField()),
                ('CreatedOn', models.DateTimeField(auto_now=True)),
                ('ReportCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.ReportMasterCategory')),
                ('ReportedAd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Product')),
            ],
        ),
        migrations.CreateModel(
            name='MachineReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ManufaturedDate', models.DateField(blank=True, null=True)),
                ('IsCustom', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('IdentificationNumber', models.CharField(default='', max_length=100)),
                ('Owner_nth', models.CharField(choices=[('FirstOwner', 'FirstOwner'), ('SecondOwner', 'SecondOwner'), ('ThirdOwner', 'ThirdOwner')], default='FirstOwner', max_length=20)),
                ('IsWorking', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('WorkFor1', models.CharField(default='', max_length=50)),
                ('WorkFor2', models.CharField(blank=True, max_length=50, null=True)),
                ('WorkFor3', models.CharField(blank=True, max_length=50, null=True)),
                ('WorkEfficiency', models.CharField(blank=True, max_length=100, null=True)),
                ('Power', models.CharField(blank=True, max_length=100, null=True)),
                ('Consumption', models.CharField(blank=True, max_length=50, null=True)),
                ('IsUnderWarranty', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('RemainWarranty', models.IntegerField()),
                ('Adid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.Product')),
            ],
        ),
    ]
