# Generated by Django 2.2.4 on 2020-03-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinereports',
            name='IdentificationNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='machinereports',
            name='WorkFor1',
            field=models.CharField(max_length=50),
        ),
    ]
