# Generated by Django 2.2.4 on 2020-03-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20200323_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinereports',
            old_name='Consumption',
            new_name='Fuel',
        ),
        migrations.RemoveField(
            model_name='machinereports',
            name='IsCustom',
        ),
        migrations.RemoveField(
            model_name='machinereports',
            name='IsUnderWarranty',
        ),
        migrations.RemoveField(
            model_name='machinereports',
            name='Owner_nth',
        ),
        migrations.RemoveField(
            model_name='machinereports',
            name='RemainWarranty',
        ),
        migrations.AddField(
            model_name='machinereports',
            name='Engine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
