# Generated by Django 2.2.4 on 2020-03-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20200323_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinereports',
            name='Extrainfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
